export const designTokensFonts = {
  specificTypographyBodyText1116pxRegular: {
    fontFamily: "'Poppins', 'Poppins-Regular'",
    fontSize: '16px',
    letterSpacing: '-0.3px',
    lineHeight: '22px',
    fontWeight: 400,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyBodyText2218pxRegular: {
    fontFamily: "'Poppins', 'Poppins-Regular'",
    fontSize: '18px',
    letterSpacing: '-0.4px',
    lineHeight: '26px',
    fontWeight: 400,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyButtonM16pxMedium: {
    fontFamily: "'Poppins', 'Poppins-Medium'",
    fontSize: '16px',
    letterSpacing: '-0.3px',
    lineHeight: '22px',
    fontWeight: 500,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyButtonM16pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '16px',
    letterSpacing: '-0.3px',
    lineHeight: '22px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyButtonS14pxMedium: {
    fontFamily: "'Poppins', 'Poppins-Medium'",
    fontSize: '14px',
    letterSpacing: '-0.3px',
    lineHeight: '100%',
    fontWeight: 500,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyCaption112pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '12px',
    letterSpacing: '-0.2px',
    lineHeight: '100%',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyCaption212pxRegular: {
    fontFamily: "'Poppins', 'Poppins-Regular'",
    fontSize: '12px',
    letterSpacing: '0px',
    lineHeight: '100%',
    fontWeight: 400,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyCaption312pxMedium: {
    fontFamily: "'Poppins', 'Poppins-Medium'",
    fontSize: '12px',
    letterSpacing: '0px',
    lineHeight: '100%',
    fontWeight: 500,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyCaption414pxRegular: {
    fontFamily: "'Poppins', 'Poppins-Regular'",
    fontSize: '14px',
    letterSpacing: '0px',
    lineHeight: '100%',
    fontWeight: 400,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyLabelTabbar1: {
    fontFamily: "'Poppins', 'Poppins-Medium'",
    fontSize: '16px',
    letterSpacing: '-0.3px',
    lineHeight: '22px',
    fontWeight: 500,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyLargeTitle132px: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '32px',
    letterSpacing: '-0.6px',
    lineHeight: '40px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyLargeTitle236px: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '36px',
    letterSpacing: '-0.7px',
    lineHeight: '40px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyLinkM16pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '16px',
    letterSpacing: '-0.3px',
    lineHeight: '22px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyLinkS14pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '14px',
    letterSpacing: '-0.3px',
    lineHeight: '100%',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyTitles1124pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '24px',
    letterSpacing: '-0.5px',
    lineHeight: '32px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
  specificTypographyTitles2222pxSemibold: {
    fontFamily: "'Poppins', 'Poppins-SemiBold'",
    fontSize: '22px',
    letterSpacing: '-0.4px',
    lineHeight: '32px',
    fontWeight: 600,
    display: 'inline-block',
    color: 'black',
  },
};
